main:
  - identifier: writing
    name: Writing
    url: https://girishshekhar.github.io/blog
    weight: 5
  - identifier: search
    name: Search
    url: https://girishshekhar.github.io/blog/search/
    weight: 7
  - identifier: tags
    name: Tags
    url: https://girishshekhar.github.io/blog/tags/
    weight: 8 
  - identifier: projects
    name: Projects
    url: https://girishshekhar.github.io/projects/
    weight: 9
  - identifier: speaking
    name: Speaking
    url: https://girishshekhar.github.io/speaking/
    weight: 10
  - identifier: copyright
    name: Copyright
    url: https://girishshekhar.github.io/copyright/
    weight: 11